### PR TITLE
Travis test on older R versions

### LINKED ISSUE #4: R 3.4.0 needed?
Nice project! Do you think the R >= 3.4.0 dependency could be relaxed?

### PR DESCRIPTION
**Pull request by gaborcsardi**
Trying to fix #4

### CODE REVIEW

**Comment by dirkschumacher** [comment]
I think the`DESCRIPTION` needs to be changed as well.

**Comment by gaborcsardi** [comment]
Right!

**Comment by gaborcsardi** [comment]
It seems all OK.

**Comment by dirkschumacher** [comment]
Perfect. Will merge it. In case `picosat` can solve your problem, I could try to include the missing functionality first before releasing it to CRAN.

**Comment by gaborcsardi** [comment]
I'll try it soon, and let you know if it faster than lpSolve. Probably it is, but need to try in practice.

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
